CLEANUP_OLD_CONTAINERS = True

REMOVE_OLD_CHECKPOINT = True
CHECKPOINT_DIR = "/tmp"
CHECKPOINT_NAME = "checkpoint-redis"

REGENERATE_RANDOM_DATA = True
RANDOM_DATA_JSON_PATH = "./tmp/data.json"
RANDOM_DATA_VOLUME_NAME = "redis_data_volume"

RANDOM_DATA_SIZE_MB = 100
RANDOM_DATA_KEY_COUNT = 100
