CLEANUP_OLD_CONTAINERS = True
ORIGINAL_REDIS_CONTAINER_NAME = "celestial-redis"
CLONE_REDIS_CONTAINER_NAME = "celestial-redis-clone"
TEMP_CHECK_CONTAINER_NAME = "celestial-temp-check-alpine"
TEMP_REDIS_CONTAINER_NAME = "celestial-redis-tmp"
USED_CONTAINERS = [
    ORIGINAL_REDIS_CONTAINER_NAME,
    CLONE_REDIS_CONTAINER_NAME,
    TEMP_REDIS_CONTAINER_NAME,
    TEMP_CHECK_CONTAINER_NAME,
]

REMOVE_OLD_CHECKPOINT = True
CHECKPOINT_DIR = "/tmp"
CHECKPOINT_NAME = "podman-checkpoint"

REGENERATE_RANDOM_DATA = False
RANDOM_DATA_JSON_PATH = "./tmp/data.json"
RANDOM_DATA_VOLUME_NAME = "redis_data_volume"

RANDOM_DATA_SIZE_MB = 10
RANDOM_DATA_KEY_COUNT = 100
