model = "SGP4"
bbox = [45.0, 0.0, 60.0, 25.0]
interval = 1
animation = false
hosts = ["192.168.10.3:1969", "192.168.10.4:1969"]
peeringhosts = ["192.168.10.3:1970", "192.168.10.4:1970"]
database = true
dbhost = "192.168.10.2:8000"

[sgp4params]
starttime = 2021-05-01T12:00:00+00:00

[networkparams]
islpropagation = 3.336e-6
bandwidth = 10_000_000
mincommsaltitude = 100_000
minelevation = 40
gstpropagation = 3.336e-6
groundstationconnectiontype = "all"

[computeparams]
vcpu_count = 4
mem_size_mib = 8192
disk_size_mib = 1000
ht_enabled = false
bootparams = "random.trust_cpu=on"
kernel = "vmlinux.bin"
rootfs = "sat.img"

[[shell]]
planes = 1
sats = 70
altitude = 550
inclination = 75.0
arcofascendingnodes = 360.0
eccentricity = 0.0

[[groundstation]]
name = "berlin"
lat = 52.514182
long = 13.328285

[groundstation.computeparams]
vcpu_count = 4
mem_size_mib = 4096
disk_size_mib = 1000
rootfs = "gst.img"

[[groundstation]]
name = "client"
lat = 52.514182
long = 13.328285

[groundstation.computeparams]
vcpu_count = 4
mem_size_mib = 4096
disk_size_mib = 1000
rootfs = "client.img"
